### ISSUE TITLE
iOS - Images don't load on initial page load until scroll

### ISSUE THREAD

**Issue by dustinkerstein** [bluebill1049/react-simple-img#19]
On iOS devices (so far only tested on an iPhone 5s running iOS 11.3) I can't seem to get any of the in-view images to load initially. It always requires a scroll (even the slightest triggers it). Have you ever seen that behavior?

**Comment by bluebill1049** [comment]
i have used for my project, didn't have issue. can you try out the demo see if there is an issue

https://react-simple-img.herokuapp.com/

**Comment by dustinkerstein** [comment]
Yeah, that works fine. I imagine it has to do with that same issue in #16 which I think is likely due to using an overflow div. Have you tried that?

**Comment by bluebill1049** [comment]
what do you mean overflow div? you have a link to your page?

**Comment by bluebill1049** [comment]
page looks nice :)  for ios device is using intersection observer poly-fill, because intersection observer API still under development.

https://github.com/w3c/IntersectionObserver

I reproduce the issue on my phone, is there a way you can trigger scroll event on ios device for the meantime until observer interaction is ready for iOS device with `overflow scroll`?
